### ISSUE TITLE
Проблема с приемом join-accept сообщения.

### ISSUE THREAD

**Issue by u236** [morransmith/sx127x#3]
Привет! Я только недавно начал разбираться с LoRa, и твоя либа оказалась самой понятной. Сейчас я пытаюсь "активировать" мой девайс на LoRaWan-сервере методом OTAA, в логах сервера и шлюза я вижу как мой join-reqest, так и join-accept от сервера, однако на девайсе я ответный пакет получить не могу. Подскажи пожалуйста, что нужно делать, чтобы получить ответ от сервера? 

В упрощенном виде мой код сейчас работает так:

1 - инициализируем структуры spi, common и т.д. (как в README проекта)
2 - инициализируем трансивер с использованием этих структур (как в README проекта)
3 - формируем join-request пакет
4 - отправляем его посредством **sx127x_transmit**
5 - включаем прерывания по приему с помощью **sx127x_receive_continuous_it**

Прерывания от DIO0, 1 и 3 работают, иногда я даже "ловлю" какие-то пакеты в сети, но ответа на join-request получить не могу. Буду очень благодарен за любую помощь. Для удобства можно пообщаться реалтаймно в телеграме, вк или еще где-нибудь.

**Comment by morransmith** [comment]
Привет, можешь обращаться в телеграм t.me/morran

**Comment by u236** [comment]
разобрался, нужно было выставить бит InvertIQ в регистре 0x33
